# Generated by Django 5.0.6 on 2024-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantitate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='descriere',
            field=models.CharField(default='...', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='imagine_produs',
            field=models.ImageField(default='imagini_produs/no_img_available.jpg', upload_to='imagini_produs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='pret',
            field=models.IntegerField(default=1),
        ),
    ]
