# Generated by Django 5.0.6 on 2024-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_cart_item_cart_remove_cart_item_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagine_produs',
            field=models.ImageField(default='imagini_produs/no_img_available.jpg', upload_to='imagini_produs/'),
        ),
    ]
